name: new_app
description: "Empowering artisans with a voice, this Android app prototype transforms product listing into a seamless, speech-driven experience, making digital selling accessible and intuitive for everyone."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  provider: ^6.1.2
  go_router: ^17.1.0
  google_generative_ai: ^0.4.7
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.0
  flutter_tts: ^4.2.5
  speech_to_text: ^7.3.0
  image_picker: ^1.2.1
  flutter_dotenv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
